### ISSUE TITLE
PodStatus's podIP and hostIP attributes are not set on readNamespacedPod(...)

### ISSUE THREAD

**Issue by anthonyyangdev** [haxsaw/hikaru#34] opened 2023-04-26 23:43 UTC
I am using `hikaru.model.rel_1_26.v1`

The values `pod.status.podIP` and `pod.status.hostIP` returned by `pod = Pod.readNamespacedPod()` or `pod.read()` are always `None` when the pod is actively running in a cluster.

I believe the issue occurs here: https://github.com/haxsaw/hikaru/blob/d1a00be3066bf5655cb2201bfa80f0e084ca576a/hikaru/meta.py#L988-L992

The pod status JSON from underlying Kubernetes call has the keys `pod_ip` and `host_ip`, while the field names in `PodStatus` are `podIP` and `hostIP`. It looks like the code in the link tries to find the key `camel_to_pep8(class_field_name)` in the JSON response, but `camel_to_pep8(podIP)` and `camel_to_pep8(hostIP)` return `pod_i_p` and `host_i_p`

**Comment by haxsaw** [comment] 2023-04-27 09:23
Arg; I'm pretty sure I know where this is happening; I'll have a look. Thanks so much for the detailed ticket.

**Comment by haxsaw** [comment] 2023-04-28 15:05
Yeah, the issue is where I thought & you tracked down; thanks again for that. Putting together fixes and new tests for this case, then I'll be starting the full set of tests across all versions of K8s/Python prior to releaes.

**Comment by haxsaw** [comment] 2023-04-29 15:16
OK, v1.0.1 just went out on all the channels. Tests added to ensure we don't regress. Closing this one out.

**Closed by haxsaw** 2023-04-29 15:16 UTC
